name: "[schedule] 1x/daily @late night"
# watch.js
# purge.js
# mainpageImages.js
# fixRedirectCategory.js

on:
  schedule:
    - cron: "35 16 * * *" # 00:35 CST
    - cron: "35 17 * * *" # 01:35 CST
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        default: "none"
        options:
          - "none"
          - "watch"
          - "purge"
          - "mainpage-image-protection"
          - "fix-redirect-category"
      group:
        type: choice
        required: true
        default: "none"
        options:
          - "none"
          - "all"

env:
  MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}

jobs:
  watch:
    if: |
      github.event.schedule == '35 16 * * *' || 
      github.event.inputs.task == 'watch' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run watch.js
        env:
          ZH_MAIN: ${{ secrets.ZH_MAIN }}
        run: node src/watch.js

  purge:
    if: |
      github.event.schedule == '35 16 * * *' || 
      github.event.inputs.task == 'purge' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run purge.js
        env:
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
        run: node src/purge.js

  mainpage-image-protection:
    if: |
      github.event.schedule == '35 16 * * *' || 
      github.event.inputs.task == 'mainpage-image-protection' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run mainpageImages.js
        env:
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
          CM_ABOT: ${{ secrets.CM_ABOT }}
        run: node src/mainpageImages.js

  fix-redirect-category:
    if: |
      github.event.schedule == '35 17 * * *' || 
      github.event.inputs.task == 'fix-redirect-category' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run fixRedirectCategory.js
        env:
          ZH_BOT: ${{ secrets.ZH_BOT }}
          CM_BOT: ${{ secrets.CM_BOT }}
        run: node src/fixRedirectCategory.js
