name: "[schedule] 1x/daily @early morning"
# sandbox.js
# brokenRedirectDelete.js
# checkActivities.js

on:
  schedule:
    - cron: "50 20 * * *"
    # 04:50 CST
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        default: "none"
        options:
          - "none"
          - "clean-sandbox"
          - "broken-redirect-deletion"
          - "check-activities"
      group:
        type: choice
        required: true
        default: "none"
        options:
          - "none"
          - "all"

env:
  MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}

jobs:
  clean-sandbox:
    if: |
      github.event_name == 'schedule' ||
      github.event.inputs.task == 'clean-sandbox' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Script
        env:
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
        run: node src/sandbox.js

  broken-redirect-deletion:
    if: |
      github.event_name == 'schedule' ||
      github.event.inputs.task == 'broken-redirect-deletion' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Script
        env:
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
        run: node src/brokenRedirectDelete.js

  check-activities:
    if: |
      github.event_name == 'schedule' ||
      github.event.inputs.task == 'check-activities' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Script
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
          CM_IBOT: ${{ secrets.CM_IBOT }}
        run: node src/checkActivities.js
