name: "[daily] 1x @early morning"
# Clean/sandbox.js
# Clean/brokenRedirectDelete.js
# Activity/maintainer.js

on:
  schedule:
    - cron: "50 20 * * *" # 04:50 CST
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        options:
          - "clean-sandbox"
          - "broken-redirect-deletion"
          - "check-activities"

env:
  MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}

jobs:
  clean-sandbox:
    if: |
      github.event_name == 'schedule' ||
      github.event.inputs.task == 'clean-sandbox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Script
        env:
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
        run: node src/Clean/sandbox.js

  broken-redirect-deletion:
    if: |
      github.event_name == 'schedule' ||
      github.event.inputs.task == 'broken-redirect-deletion'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Script
        env:
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
        run: node src/Clean/brokenRedirectDelete.js

  check-activities:
    if: |
      github.event_name == 'schedule' ||
      github.event.inputs.task == 'check-activities'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Script
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
          CM_IBOT: ${{ secrets.CM_IBOT }}
        run: node src/Activity/maintainer.js
