name: "[schedule] monthly"
# newsSubscriber.js @2nd
# newsProtect.js @9th
# updateOverrideCategory.js @3rd

on:
  schedule:
    - cron: "50 16 1 * *" # 2nd 00:50 CST
    - cron: "50 16 2 * *" # 3rd 00:50 CST
    - cron: "50 16 8 * *" # 9th 00:50 CST
    - cron: "50 16 9,24 * *" # 10th, 25th 00:50 CST
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        default: "none"
        options:
          - "none"
          - "news-subscriber"
          - "news-protection"
          - "interface-messages"
          - "update-override-category"
      group:
        type: choice
        required: true
        default: "none"
        options:
          - "none"
          - "news"
          - "all"

env:
  MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  news-subscriber:
    runs-on: ubuntu-latest
    if: |
      github.event.schedule == '50 16 1 * *' || 
      github.event.inputs.task == 'news-subscriber' ||
      github.event.inputs.group == 'news' ||
      github.event.inputs.group == 'all'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run newsSubscriber.js
        env:
          ZH_BOT: ${{ secrets.ZH_BOT }}
        run: node src/newsSubscriber.js

  news-protection:
    runs-on: ubuntu-latest
    if: |
      github.event.schedule == '50 16 8 * *' || 
      github.event.inputs.task == 'news-protection' ||
      github.event.inputs.group == 'news' ||
      github.event.inputs.group == 'all'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run newsProtect.js @9th
        env:
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
        run: node src/newsProtect.js

  update-override-category:
    runs-on: ubuntu-latest
    if: |
      github.event.schedule == '50 16 2 * *' ||
      github.event.inputs.task == 'update-override-category' ||
      github.event.inputs.group == 'all'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run updateOverrideCategory.js @3rd
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
        run: node src/updateOverrideCategory.js

  interface-messages:
    runs-on: ubuntu-latest
    if: |
      github.event.schedule == '50 16 9,24 * *' ||
      github.event.inputs.task == 'interface-messages' ||
      github.event.inputs.group == 'all'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run interfaceMessages.js
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
          CM_IBOT: ${{ secrets.CM_IBOT }}
        run: node src/interfaceMessages.js
